functionsDirectory = "C:\\Users\\Fabian\\OneDrive\\Escritorio\\Proyecto paginas web\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\Fabian\\OneDrive\\Escritorio\\Proyecto paginas web"
publishOrigin = "default"
functions = "C:\\Users\\Fabian\\OneDrive\\Escritorio\\Proyecto paginas web\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"